project_id = "neujvcpyjtrgiteqhgck"

[functions.send-message]
verify_jwt = true

[functions.webhook-meta]
verify_jwt = false

[functions.webhook-zapi]
verify_jwt = false

[functions.webhook-n8n-instance]
verify_jwt = false

[functions.webhook-leads]
verify_jwt = false

[functions.test-llm-connection]
verify_jwt = true

[functions.test-evolution-connection]
verify_jwt = true

[functions.wa-process-buffer]
verify_jwt = false

[functions.ai-process]
verify_jwt = false
