project_id = "neujvcpyjtrgiteqhgck"

[functions.send-message]
verify_jwt = true

[functions.webhook-meta]
verify_jwt = false

[functions.webhook-zapi]
verify_jwt = false

[functions.webhook-n8n-instance]
verify_jwt = false
